apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - mysql-secret.yaml
  - mysql-pv.yaml
  - mysql-deployment.yaml
  - registry-pv.yaml
  - registry-deployment.yaml
  - todo-deployment.yaml
  - todo-ingress.yaml
